version: "2"
services:
  front_end:
    depends_on:
      - api
    extends:
      file: ../../mf_frontend/docker/docker-compose.yml
      service: mf_frontend
    container_name: mf_frontend

  workflows:
    extends:
      file: ../../mf_workflows/docker/docker-compose.yml
      service: workflows
    environment:
      LOGGING_USE_JASON: "true"
      LOGGING_LEVEL: silly
    container_name: mf_workflows

  projections:
    extends:
      file: ../../mf_projections/docker/docker-compose.yml
      service: projections
    environment:
      LOGGING_USE_JASON: "true"
      LOGGING_LEVEL: silly
    container_name: mf_projections

  api:
    extends:
      file: ../../mf_api/docker/docker-compose.yml
      service: api
    environment:
      LOGGING_USE_JASON: "true"
      LOGGING_LEVEL: silly
    container_name: mf_api
