version: "2"
services:
  node:
    build:
      context: ../nodeDocker/
      dockerfile: Dockerfile
  data:
    build:
      context: ../../mf_data/
      dockerfile: docker/Dockerfile
    depends_on:
      - node
      - postgres
      - eventstore
    extends:
      file: ../../mf_data/docker/docker-compose.yml
      service: data
    environment:
      NODE_ENV: "dev"

  postgres:
    image: postgres
    ports:
      - 5400:5432
    env_file:
      - ./.env
 
  eventstore:
    image: eventstore/eventstore
    ports:
      - 2113:2113
      - 1113:1113
    environment:
      - ext-http-prefixes=http://*:2113/
      - ext-ip="0.0.0.0"
      - log=/data/logs
      - stats-period-sec=3000000
    volumes:
      - eventstore:/var/lib/eventstore

#      - run-projections=all

#  elasticsearch:
#    build: ../elasticsearch/
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
#    container_name: mf_elasticsearch
#    volumes:
#      - elastic:/var/lib/elastic
#
#  logstash:
#    build: ../logstash/
#    command: -f /etc/logstash/conf.d/
#    volumes:
#      - ./../logstash/config:/etc/logstash/conf.d
#    ports:
#      - "5000:5000"
#    depends_on:
#      - elasticsearch
#    container_name: mf_logstash
#  kibana:
#    build: ../kibana/
#    volumes:
#      - ./../kibana/config/:/etc/kibana/
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#    container_name: mf_kibana
#
volumes:
  postgres_data:
  eventstore:
#  elastic: