version: "2"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - LANG=en_US.UTF-8
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=methodfitness
    ports:
      - 5432:5432
 
  eventstore:
    image: eventstore/eventstore
    container_name: eventstore
    ports:
      - 2113:2113
      - 1113:1113
    environment:
      - ext-http-prefixes=http://*:2113/
      - ext-ip="0.0.0.0"
      - db=/data/db    
      - log=/data/logs
      - stats-period-sec=30000
#      - run-projections=all
